use crate::traits::ScrollOutput;

/// Magic marker attached to injected wheel events.
///
/// The hook uses this to avoid re-processing events generated by ourselves.
#[cfg(target_os = "windows")]
pub const INJECT_MAGIC: usize = 0x5353_4352_4F4C_4C31; // "SSCROLL1"

#[cfg(target_os = "windows")]
pub struct WindowsScrollOutput;

#[cfg(target_os = "windows")]
impl WindowsScrollOutput {
    pub fn new() -> Self {
        Self
    }
}

#[cfg(target_os = "windows")]
impl ScrollOutput for WindowsScrollOutput {
    fn inject_wheel(&self, delta_x: i32, delta_y: i32) {
        use std::mem::size_of;
        use windows_sys::Win32::UI::Input::KeyboardAndMouse::{
            SendInput, INPUT, INPUT_0, INPUT_MOUSE, MOUSEEVENTF_HWHEEL, MOUSEEVENTF_WHEEL,
            MOUSEINPUT,
        };

        let mut inputs = Vec::with_capacity(2);

        if delta_y != 0 {
            inputs.push(INPUT {
                r#type: INPUT_MOUSE,
                Anonymous: INPUT_0 {
                    mi: MOUSEINPUT {
                        dx: 0,
                        dy: 0,
                        mouseData: delta_y as u32,
                        dwFlags: MOUSEEVENTF_WHEEL,
                        time: 0,
                        dwExtraInfo: INJECT_MAGIC,
                    },
                },
            });
        }

        if delta_x != 0 {
            inputs.push(INPUT {
                r#type: INPUT_MOUSE,
                Anonymous: INPUT_0 {
                    mi: MOUSEINPUT {
                        dx: 0,
                        dy: 0,
                        mouseData: delta_x as u32,
                        dwFlags: MOUSEEVENTF_HWHEEL,
                        time: 0,
                        dwExtraInfo: INJECT_MAGIC,
                    },
                },
            });
        }

        if !inputs.is_empty() {
            // SAFETY: `inputs` points to a valid contiguous buffer and size matches `INPUT`.
            unsafe {
                let sent = SendInput(
                    inputs.len() as u32,
                    inputs.as_ptr(),
                    size_of::<INPUT>() as i32,
                );
                if sent != inputs.len() as u32 {
                    eprintln!(
                        "[butter-scroll] SendInput partial/failed: sent {sent} of {}",
                        inputs.len()
                    );
                }
            }
        }
    }
}

#[cfg(not(target_os = "windows"))]
pub struct WindowsScrollOutput;

#[cfg(not(target_os = "windows"))]
impl WindowsScrollOutput {
    pub fn new() -> Self {
        Self
    }
}

#[cfg(not(target_os = "windows"))]
impl ScrollOutput for WindowsScrollOutput {
    fn inject_wheel(&self, _delta_x: i32, _delta_y: i32) {
        // no-op on non-Windows
    }
}
